package de.tu_darmstadt.cbs.emailsmpc;

public enum AppState {
    NONE, STARTING, PARTICIPATING, ENTERING_VALUES, INITIAL_SENDING, SENDING_SHARE, RECIEVING_SHARE, SENDING_RESULT, RECIEVING_RESULT, FINISHED
}
